# Generated by Django 5.2.17 on 2026-09-12 05:05

import tracker.models
from zoneinfo import ZoneInfo
from django.db import migrations, models


def backfill_months(apps, schema_editor):
    Tracker = apps.get_model("tracker", "Tracker")
    UploadIntent = apps.get_model("tracker", "UploadIntent")
    db = schema_editor.connection.alias
    jakarta = ZoneInfo("Asia/Jakarta")
    for tracker in Tracker.objects.using(db).iterator():
        month = tracker.created_at.astimezone(jakarta).date().replace(day=1)
        Tracker.objects.using(db).filter(pk=tracker.pk).update(order_month=month)
    for intent in UploadIntent.objects.using(db).select_related("photo__tracker").iterator():
        if intent.photo_id:
            month = intent.photo.tracker.order_month
        else:
            target = Tracker.objects.using(db).filter(owner_id=intent.owner_id, order_id=intent.order_id).first()
            month = target.order_month if target else intent.created_at.astimezone(jakarta).date().replace(day=1)
        UploadIntent.objects.using(db).filter(pk=intent.pk).update(order_month=month)


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tracker',
            name='unique_owner_order',
        ),
        migrations.AddField(
            model_name='tracker',
            name='order_month',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='uploadintent',
            name='order_month',
            field=models.DateField(null=True),
        ),
        migrations.RunPython(backfill_months, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='tracker', name='order_month',
            field=models.DateField(default=tracker.models.current_order_month),
        ),
        migrations.AlterField(
            model_name='uploadintent', name='order_month',
            field=models.DateField(default=tracker.models.current_order_month),
        ),
        migrations.AddConstraint(
            model_name='tracker',
            constraint=models.UniqueConstraint(fields=('owner', 'order_id', 'order_month'), name='unique_owner_order_month'),
        ),
    ]
